title: TLS Counseling
email: your-email@example.com
description: >- 
  Terrence Salley, LPC, SEP, is a Licensed Professional Counselor and Somatic Experiencing Practitioner.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
include:
  - _redirects
  - CNAME
  - admin
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier

# Sass settings
sass:
  style: compressed
  sourcemap: never

# Minifier settings
jekyll-minifier:
  uglifier_args:
    harmony: true
  compress_css: true
  compress_javascript: true
  compress_json: true
  exclude:
    - 'assets/**/*.js'

# Server settings
port: 4000
host: 0.0.0.0
livereload: true