name: Build & Deploy 11ty Site

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build 11ty
        run: npm run build

      # This is an explicit declaration of the dependency that's failing
      - name: Setup artifact action
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            fs.mkdirSync('./_site_artifact', { recursive: true });
            fs.writeFileSync('./_site_artifact/artifact.tar', await require('@actions/artifact').create().uploadArtifact('github-pages', ['./_site'], null, {});
      
      - name: Upload artifact directly
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const globber = require('@actions/glob');
            const paths = await globber.create('_site/**').glob();
            await require('@actions/artifact').create().uploadArtifact('github-pages', paths, '_site', {});
            
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
